version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: scheduler_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - scheduler-net

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    networks:
      - scheduler-net

volumes:
  pgdata:

networks:
  scheduler-net:
    driver: bridge
